### ISSUE TITLE
Great paper could you explain how to use it

### ISSUE THREAD

**Issue by leolove2022** [CRANK-MS/CRANK-MS#1]
I have read your paper, which is excellent. 
Could you further introduce how to use it ?

**Comment by xf3227** [comment]
Hello Leoloeve, thank you for your interest in our project. We appreciate your feedback and will be dedicating time to expand the README to provide more comprehensive information. Could you please share any specific concerns or areas you'd like us to focus on? This will assist us in addressing your needs more directly.

**Comment by leolove2022** [comment]
Hi Chonghua,

Thank you for your reply.
I have gotten some LCMS data and analysis them through XCMS website. 
Currently I want to annotate each MS peak and also want to further screen the peak quality.

I find your project may have this kind of function but after I install it, I didn’t know how to input my database or do any processing.

Best,
Xuchao

**Comment by xf3227** [comment]
Hi Xuchao, before updating the README file, I believe it would be beneficial for us to briefly walk through the training process here. Essentially, our implementation has the same interfaces of Scikit-learn models. So, if you're familiar with using Scikit-learn models, you should find our process quite straightforward. Basically,

```
from crankms import MLPClassifier as MLP
model = MLP(
            dense_dims = (32,),
            num_epochs = 64,
            batch_size = 16,
            lambda_l1 = 0,
            lambda_l2 = 0, 
            device = 'cpu'
)
model.fit(x_train, y_train)
pred = model.predict(x_test)
```

You may want to replace with your own hyperparameters though. BTW, besides fit() and predict(), it also supports predicts_proba(), load(), save().

**Comment by leolove2022** [comment]
Cool. I will try it first and give you a feedback. 
Thanks
