### ISSUE TITLE
How to calculate average absolute SHAP values?

### ISSUE THREAD

**Issue by DylanGuo1101** [CRANK-MS/CRANK-MS#3]
Dear author,

I have recently read your published literature, which is a great idea in medicine. I would like to know how to calculate the average absolute SHAP values. Is it correct to calculate the SHAP after each model establishment, and then separate the average absolute values based on the positive and negative classes? Please advise.

Thank you!

**Comment by diana1806** [comment]
Hi @DingfanGuo,
Thank you for your interest in our work!
I believe my co-author, Chonghua has responded to your query via email.
Please let us know if you have any further questions.
